[settings]
experimental = true
shims_dir = "~/.rtx/shims"

[tools]
bat = "latest"
buf = "latest"
direnv = "latest"
dust = "latest"
exa = "latest"
golang = "latest"
jq = "latest"
nodejs = "lts"
python = "latest"
rclone = "latest"
shellcheck = "latest"
shfmt = "latest"
starship = "latest"
