cask_args appdir: '/Applications'
tap 'goreleaser/tap'
tap 'homebrew/cask-drivers'
tap 'homebrew/cask'


#
# Command-Line Tools (Brew)
#

brew 'ack'
brew 'ansible'
brew 'aspell', args: ['with-lang-el', 'with-lang-sv']
brew 'bash'
brew 'bazaar'
brew 'colordiff'
brew 'ctop'
brew 'dep'
brew 'dpkg'
brew 'geckodriver'
brew 'git-crypt'
brew 'git-standup'
brew 'git'
brew 'global', args: ['with-ctags', 'with-pygments']
brew 'go'
brew 'goreleaser'
brew 'heroku'
brew 'htop'
brew 'httpie'
brew 'jq'
brew 'kubernetes-cli'
brew 'kubernetes-helm'
brew 'less'
brew 'lua'
brew 'luarocks'
brew 'mysql'
brew 'openshift-cli'
brew 'peco'
brew 'pyenv'
brew 'rbenv'
brew 'rclone'
brew 'readline'
brew 'reattach-to-user-namespace'
brew 'redis'
brew 'ruby-build'
brew 'shellcheck'
brew 'source-highlight'
brew 'the_silver_searcher'
brew 'tmux'
brew 'tree'
brew 'watch'
brew 'wget'
brew 'yank'
brew 'yarn'
brew 'zsh'

cask 'osxfuse'
brew 'sshfs'


#
# Desktop Apps (Cask)
#

# Core Apps
cask '1password'
cask 'aerial'
cask 'alfred'
cask 'appcleaner'
cask 'bartender'
cask 'betterzip'
cask 'emacs'
cask 'firefox'
cask 'fluid'
cask 'flux'
cask 'google-chrome'
cask 'gpg-suite'
cask 'hammerspoon'
cask 'iina'
cask 'istat-menus'
cask 'iterm2'
cask 'karabiner-elements'
cask 'logitech-gaming-software'
cask 'logitech-options'
cask 'mplayerx'
cask 'qlcolorcode'
cask 'qlmarkdown'
cask 'qlstephen'
cask 'resolutionator'
cask 'stay'
cask 'ubersicht'
cask 'vlc'

# Work Apps
cask 'atom'
cask 'bbedit'
cask 'chromedriver'
cask 'cyberduck'
cask 'dash'
cask 'docker'
cask 'fork'
cask 'github'
cask 'google-cloud-sdk'
cask 'insomnia'
cask 'java'
cask 'kaleidoscope'
cask 'licecap'
cask 'minikube'
cask 'minishift'
cask 'muzzle'
cask 'paw'
cask 'postico'
cask 'postman'
cask 'robo-3t'
cask 'rowanj-gitx'
cask 'sequel-pro'
cask 'slack'
cask 'transmit'
cask 'vagrant'
# cask 'virtualbox'
cask 'visual-studio-code'

# Personal Apps
if `hostname -s`.strip == 'noct'
  cask '4k-video-downloader'
  cask 'android-file-transfer'
  cask 'android-platform-tools'
  cask 'audio-hijack'
  cask 'autodmg'
  cask 'boom-3d'
  cask 'calibre'
  cask 'chicken'
  cask 'daisydisk'
  cask 'deluge'
  cask 'discord'
  cask 'dropbox'
  cask 'etcher'
  cask 'filebot'
  cask 'gog-galaxy'
  cask 'google-photos-backup-and-sync'
  cask 'hackety-hack'
  cask 'handbrake'
  cask 'irccloud'
  cask 'istumbler'
  cask 'keybase'
  cask 'kindle'
  cask 'little-snitch'
  cask 'makemkv'
  cask 'messenger'
  cask 'micro-snitch'
  cask 'monodraw'
  cask 'omnigraffle'
  cask 'openemu'
  cask 'parallels'
  cask 'peakhour'
  cask 'plex-media-player'
  cask 'pocket-casts'
  cask 'qlimagesize'
  cask 'qlprettypatch'
  cask 'qlvideo'
  cask 'quicklook-csv'
  cask 'quicklook-json'
  cask 'quicklookapk'
  cask 'rclone-browser'
  cask 'ring'
  cask 'sixtyforce'
  cask 'skyfonts'
  cask 'skype'
  cask 'soulver'
  cask 'spotify'
  cask 'suspicious-package'
  cask 'teamviewer'
  cask 'transmission'
  cask 'virtualc64'
  cask 'viscosity'
  cask 'vmware-fusion'
  cask 'vnc-viewer'
  cask 'wavebox'
  cask 'webpquicklook'
  cask 'witgui'
  cask 'xld'
  cask 'yakyak'
end
