set -g @chroma_preset      'cornflower'
set -g @chroma_background  'dark'
set -g @chroma_mode        'auto'
set -g @chroma_powerline   'off'
set -g @chroma_show_cpu    'on'
set -g @chroma_show_memory 'on'
set -g @chroma_show_disk   'off'