# ------------------------------------------------------------------------------
# jimeh's Starship Config
# ------------------------------------------------------------------------------
# Version: 0.6.1
# URL: https://github.com/jimeh/dotfiles/blob/main/config/starship.toml
# ------------------------------------------------------------------------------
# Two-line Starship (https://starship.rs/) prompt. Line 1 has directory, git
# info, tool/language metadata, user@host, and timestamp. Line 2 has the
# prompt character. Most modules are disabled for easy cherry picking.
# ------------------------------------------------------------------------------

# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# ------------------------------------------------------------------------------
# MARK: Format
# ------------------------------------------------------------------------------

add_newline = true

format = """\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$hg_branch\
$fossil_branch\
$fossil_metrics\
$hg_state\
$direnv\
$mise\
$nats\
$jobs\
$netns\
$shell\
$memory_usage\
$os\
$fill\
(\
$localip\
$shlvl\
$singularity\
$kubernetes\
$vcsh\
$pijul_channel\
$docker_context\
$package\
$nix_shell\
$pixi\
$conda\
$meson\
$xmake\
$spack\
$aws\
$gcloud\
$helm\
$openstack\
$azure\
$env_var\
$custom\
[ ·](fg:243))\
(\
$c\
$cpp\
$cmake\
$cobol\
$daml\
$dart\
$deno\
$dotnet\
$elixir\
$elm\
$erlang\
$fennel\
$fortran\
$gleam\
$golang\
$guix_shell\
$haskell\
$haxe\
$java\
$julia\
$kotlin\
$gradle\
$lua\
$mojo\
$nim\
$nodejs\
$bun\
$ocaml\
$opa\
$perl\
$php\
$pulumi\
$purescript\
$python\
$quarto\
$raku\
$rlang\
$red\
$ruby\
$rust\
$scala\
$solidity\
$swift\
$terraform\
$typst\
$vlang\
$vagrant\
$zig\
$buf\
$crystal\
[ ·](fg:243))\
$username\
$hostname\
$container\
$time\
$line_break\
$sudo\
$character\
"""

right_format = """\
$battery\
$cmd_duration\
$status\
"""

# ------------------------------------------------------------------------------
# MARK: Prompt Layout
# ------------------------------------------------------------------------------

[directory]
truncate_to_repo = false
truncation_length = 99
format = '[$path]($style)[$read_only]($read_only_style)'
style = ''
read_only = '󰌾'
read_only_style = 'bold red'

[fill]
symbol = ' '

[username]
disabled = false
show_always = true
format = '( [$user]($style))'
style_user = 'fg:243'
style_root = 'bold fg:196 bg:52'

[hostname]
disabled = false
ssh_only = false
format = '([@](fg:243)[$hostname]($style))'
style = 'fg:243'

[container]
format = '(:[$symbol \[$name\]]($style))'
style = 'fg:246'
disabled = false

[time]
format = '( [\[](fg:239)[$time]($style)[\]](fg:239))'
style = "bold fg:243"
disabled = false

[line_break]
disabled = false

[sudo]
symbol = ' '
format = '[$symbol]($style)'
style = 'bold dimmed red'
disabled = false

[character]
success_symbol = '[❯](bold fg:118)'
error_symbol = '[❯](bold fg:46)'
vimcmd_symbol = '[❮](bold fg:46)'

# ------------------------------------------------------------------------------
# MARK: Source Control
# ------------------------------------------------------------------------------

[git_branch]
format = '( [$symbol$branch]($style))'
style = 'fg:51'
symbol = ''
truncation_length = 24

[git_commit]
tag_symbol = ''
format = '[\($hash$tag\)]($style)'
style = 'bold fg:213'
only_detached = true
tag_disabled = false

[git_state]
format = '\[[$state($progress_current/$progress_total)]($style)\]'
style = 'bold fg:208'

[git_metrics]
added_style = 'bold fg:148'
deleted_style = 'bold fg:196'
format = '([\[](fg:51)([+$added]($added_style))([-$deleted]($deleted_style))[\]](fg:51))'
disabled = true

[git_status]
format = '([$all_status$ahead_behind]($style))'
style = 'bold fg:201'
stashed = ''
ahead = ""
behind = ''
modified = '!'
untracked = '?'
diverged = ''
deleted = '✖'

[hg_branch]
format = '([$symbol$branch]($style))'
style = 'fg:51'
symbol = ''
truncation_length = 24

[fossil_branch]
symbol = ''
format = '( [$symbol$branch]($style))'
disabled = true

[fossil_metrics]
format = '([\[](fg:51)([+$added]($added_style))([-$deleted]($deleted_style))[\]](fg:51))'
disabled = true

[hg_state]
format = '\[[$state($progress_current/$progress_total)]($style)\]'
style = 'bold fg:208'
disabled = true

[pijul_channel]
symbol = ' '
format = '( [$symbol$channel]($style))'
disabled = true

# ------------------------------------------------------------------------------
# MARK: Status & Info
# ------------------------------------------------------------------------------

[shlvl]
symbol = ' '
format = '( [$symbol$shlvl]($style))'
disabled = true

[cmd_duration]
format = '( [\(](fg:242)[$duration]($style)[\)](fg:242))'
style = 'bold fg:220'

[status]
symbol = ''
# success_symbol = '' # enable showing success symbol
not_executable_symbol = ''
not_found_symbol = ''
sigint_symbol = ''
signal_symbol = '󱐋'
format = '( [\[](fg:239)[$symbol$status]($style)[\]](fg:239))'
style = 'bold red'
success_style = 'bold green'
disabled = false

[jobs]
symbol = '✦'
format = '( [$symbol$number]($style))'
style = 'bold blue'
symbol_threshold = 1
number_threshold = 1
disabled = false

[shell]
bash_indicator = ' bsh'
fish_indicator = ' fsh'
zsh_indicator = ' zsh'
powershell_indicator = ' psh'
ion_indicator = " ion"
elvish_indicator = ' esh'
tcsh_indicator = ' tsh'
xonsh_indicator = ' xsh'
cmd_indicator = ' cmd'
nu_indicator = ' nu'
format = '[$indicator]($style)'
disabled = true

[localip]
format = '( @[$localipv4](bold red))'
disabled = true

[os]
format = '( [$symbol]($style))'
disabled = true

[battery]
format = '( [$symbol$percentage]($style))'

[[battery.display]]
threshold = 20
style = 'bold red'

[memory_usage]
threshold = 75
symbol = '󰍛 '
format = '( [$symbol${ram}]($style))'
disabled = true

# ------------------------------------------------------------------------------
# MARK: Languages
# ------------------------------------------------------------------------------

[buf]
symbol = ' '
format = '( [$symbol($version)]($style))'
disabled = false

[bun]
symbol = ' '
format = '( [$symbol$version]($style))'
style = 'bold blue'
disabled = false

[c]
symbol = ' '
format = '( [$symbol($version(-$name))]($style))'
disabled = true

[cpp]
symbol = ' '
format = '( [$symbol($version(-$name))]($style))'
disabled = true

[cmake]
symbol = ' '
format = '( [$symbol$version]($style))'
disabled = true

[cobol]
symbol = '󰒓 '
format = '( [$symbol$version]($style))'
disabled = true

[crystal]
symbol = ' '
format = '( [$symbol$version]($style))'
disabled = false

[daml]
format = '( [$symbol($version)]($style))'
disabled = true

[dart]
symbol = ' '
format = '( [$symbol$version]($style))'
disabled = false

[deno]
symbol = ' '
format = '( [$symbol$version]($style))'
disabled = false

[dotnet]
symbol = '󰪮 '
format = '( [$symbol($version)( 🎯 $tfm)]($style))'
disabled = false

[elixir]
symbol = ' '
format = '( [$symbol($version \(OTP $otp_version\))]($style))'
disabled = false

[elm]
symbol = ' '
format = '( [$symbol$version]($style))'
disabled = true

[erlang]
symbol = ' '
format = '( [$symbol$version]($style))'
disabled = true

[fennel]
symbol = ' '
format = '( [$symbol($version)]($style))'
disabled = true

[fortran]
symbol = ' '
format = '( [$symbol$version]($style))'
disabled = true

[gleam]
format = '( [$symbol($version)]($style))'
disabled = false

[golang]
symbol = ' '
format = '( [$symbol$version]($style))'
disabled = false

[guix_shell]
symbol = ' '
format = '( [$symbol]($style))'
disabled = true

[haskell]
symbol = ' '
format = '( [$symbol($version)]($style))'
disabled = false

[haxe]
symbol = ' '
format = '( [$symbol($version)]($style))'
disabled = true

[java]
symbol = ' '
format = '( [$symbol$version]($style))'
disabled = true

[julia]
symbol = ' '
format = '( [$symbol$version]($style))'
disabled = true

[kotlin]
symbol = ' '
format = '( [$symbol$version]($style))'
disabled = true

[lua]
symbol = ' '
format = '( [$symbol$version]($style))'
disabled = false

[mojo]
format = '( [$symbol$version]($style))'
disabled = true

[nim]
symbol = '󰆥 '
format = '( [$symbol$version]($style))'
disabled = true

[nodejs]
symbol = ' '
format = '( [$symbol$version]($style))'
disabled = false

[ocaml]
symbol = ' '
format = '( [$symbol$version(\($switch_indicator$switch_name\))]($style))'
disabled = true

[perl]
symbol = ' '
format = '( [$symbol$version]($style))'
disabled = true

[php]
symbol = ' '
format = '( [$symbol$version]($style))'
disabled = false

[purescript]
format = '( [$symbol$version]($style))'
disabled = true

[python]
symbol = ' '
format = '( [${symbol}${pyenv_prefix}${version}( \($virtualenv\))]($style))'
disabled = true

[raku]
format = '( [$symbol($version-$vm_version)]($style))'
disabled = true

[rlang]
symbol = '󰟔 '
format = '( [$symbol$version]($style))'
disabled = true

[red]
format = '( [$symbol$version]($style))'
disabled = true

[ruby]
symbol = ' '
# symbol = ' ' # alternative symbol
format = '( [$symbol$version]($style))'
disabled = false

[rust]
symbol = '󱘗 '
format = '( [$symbol$version]($style))'
disabled = false

[scala]
symbol = ' '
format = '( [$symbol$version]($style))'
disabled = true

[solidity]
format = '( [$symbol$version]($style))'
disabled = false

[swift]
symbol = ' '
format = '( [$symbol$version]($style))'
disabled = false

[vlang]
format = '( [$symbol$version]($style))'
disabled = true

[zig]
symbol = ' '
format = '( [$symbol$version]($style))'
disabled = false

# ------------------------------------------------------------------------------
# MARK: Tools
# ------------------------------------------------------------------------------

[aws]
symbol = ' '
format = '( [$symbol($profile)( \($region\))( \[$duration\])]($style))'
disabled = true

[azure]
symbol = '󰠅 '
format = '( [$symbol($subscription)]($style))'
disabled = true

[conda]
symbol = ' '
format = '( [$symbol$environment]($style))'

[direnv]
symbol = ' '
format = '( [$symbol]($style)[(($loaded/)$allowed)](red))'
allowed_msg = ''
denied_msg = 'denied'
loaded_msg = ''
not_allowed_msg = 'not allowed'
unloaded_msg = ''
disabled = false
style = 'bold green'

[docker_context]
symbol = ' '
format = '( [$symbol$context]($style))'
disabled = true

[env_var]
format = '( with [$env_value]($style))'
disabled = true

[gcloud]
symbol = ' '
format = '( [$symbol$account(@$domain)(\($region\))]($style))'
disabled = true

[gradle]
symbol = ' '
format = '( [$symbol($version)]($style))'
disabled = true

[helm]
format = '( [$symbol$version]($style))'
disabled = false

[kubernetes]
symbol = '☸ '
format = '( [$symbol$context(\($namespace\))]($style))'
disabled = false

[[kubernetes.contexts]]
context_pattern = '^orbstack$'
symbol = ''
context_alias = ''
style = ''

[meson]
symbol = '󰔷 '
format = '( [$symbol$project]($style))'
disabled = true

[xmake]
symbol = ' '
format = '( [$symbol$version]($style))'
disabled = true

[mise]
format = '( [$symbol$health]($style))'
disabled = true

[nats]
format = '( [$symbol$name]($style))'
disabled = false

[netns]
format = '( [$symbol \[$name\]]($style))'
disabled = true

[nix_shell]
symbol = ' '
format = '( [$symbol$state(\($name\))]($style))'
disabled = false

[pixi]
symbol = '󰏗 '
format = '( [$symbol$environment]($style))'
disabled = true

[opa]
format = '( [$symbol($version)]($style))'
disabled = true

[openstack]
symbol = ' '
format = '( [$symbol$cloud(\($project\))]($style))'
disabled = true

[package]
symbol = '󰏗 '
format = '( [$symbol$version]($style))'
disabled = true

[pulumi]
format = '( [$symbol$stack]($style))'
disabled = true

[quarto]
format = '( [$symbol$version]($style))'
disabled = false

[singularity]
format = '( [$symbol\[$env\]]($style))'
disabled = true

[spack]
format = '( [$symbol$environment]($style))'
disabled = true

[terraform]
format = '( [$symbol$workspace]($style))'
disabled = false

[typst]
format = '( [$symbol$version]($style))'
disabled = false

[vagrant]
format = '( [$symbol($version)]($style))'
disabled = false

[vcsh]
format = '(vcsh [$symbol$repo]($style))'
disabled = true
